[build]
  command = "pnpm run build"
  publish = "apps/finance-web-app/dist"
  ignore = "git log -1 --pretty=%B | grep -q '\\[skip deploy\\]'"

[dev]
  command = "pnpm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
