name: 🚦 CI - Build & Test

on:
  push:
    branches:
      - main

jobs:
  build:
    if: |
      contains(github.event.head_commit.message, '[skip]') == false &&
      github.event_name == 'push' &&
      (
        contains(join(github.event.head_commit.modified), 'apps/finance-api/') ||
        contains(join(github.event.head_commit.added), 'apps/finance-api/') ||
        contains(join(github.event.head_commit.removed), 'apps/finance-api/')
      )    
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: finance_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: financepassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      DATABASE_TYPE: postgres
      API_VERSION: /api/v1
      PORT: 3030
      DATABASE_URL: postgres://postgres:financepassword@localhost:5432/finance_test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Enable Corepack and prepare PNPM
        run: |
          corepack enable
          corepack prepare pnpm@10.4.1 --activate
          pnpm -v  # debug check

      - name: Install dependencies
        run: pnpm install

      - name: Build monorepo
        run: pnpm build

      - name: Wait for DB to be ready
        run: |
          echo "⏳ Waiting for Postgres..."
          until pg_isready -h localhost -p 5432; do sleep 1; done
          echo "✅ Postgres is ready"

      - name: Seed test DB (init.sql)
        run: |
          psql $DATABASE_URL -f apps/finance-api/dbinit/init.sql

      - name: Run tests (only for finance-api)
        run: pnpm --filter=finance-api test
